# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('fechaRealizacion', models.DateField(verbose_name='Fecha a realizar')),
                ('hora', models.TimeField(verbose_name='Hora de Realizacion')),
                ('descripcion', models.TextField(max_length=800)),
                ('fechaPublicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('puntuacion', models.IntegerField(default=0)),
                ('autorizado', models.SmallIntegerField(default=0)),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-fechaRealizacion'],
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Capsulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('texto', models.TextField(max_length=225)),
                ('imagen', models.ImageField(default='imgCapsula/default.jpg', upload_to='imgCapsula/')),
            ],
            options={
                'verbose_name': 'capsula',
                'verbose_name_plural': 'capsulas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('actividad', models.ManyToManyField(to='api.Actividad')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=200)),
                ('fechaComentario', models.DateField(verbose_name='Fecha del comentario')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actividad')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='imgActividad/default.jpg', upload_to='imgActividad/')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actividad')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtista', models.CharField(max_length=100)),
                ('nombreReal', models.CharField(max_length=65)),
                ('imagen', models.ImageField(default='imgPerfil/default.jpg', upload_to='imgPerfil/')),
                ('sexo', models.SmallIntegerField(default=0)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fechaRegistro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('autorizado', models.SmallIntegerField(default=0)),
                ('actividad', models.ManyToManyField(to='api.Actividad')),
                ('categoria', models.ManyToManyField(to='api.Categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechaRegistro'],
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='VisitasActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actividad')),
            ],
            options={
                'verbose_name': 'visitactividad',
                'verbose_name_plural': 'visitasactividades',
            },
        ),
        migrations.CreateModel(
            name='VisitasPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ['-fecha'],
                'verbose_name': 'visitaperfil',
                'verbose_name_plural': 'visitasperfiles',
            },
        ),
        migrations.AddField(
            model_name='comentarios',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil'),
        ),
        migrations.AddField(
            model_name='capsulas',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil'),
        ),
    ]
